package com.daxia.entity;

import java.util.Date;

public class OcrAccount {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ocr_account.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ocr_account.access_token
     *
     * @mbg.generated
     */
    private String access_token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ocr_account.expires_in
     *
     * @mbg.generated
     */
    private String expires_in;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ocr_account.effective_time
     *
     * @mbg.generated
     */
    private Date effective_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ocr_account.id
     *
     * @return the value of ocr_account.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ocr_account.id
     *
     * @param id the value for ocr_account.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ocr_account.access_token
     *
     * @return the value of ocr_account.access_token
     *
     * @mbg.generated
     */
    public String getAccess_token() {
        return access_token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ocr_account.access_token
     *
     * @param access_token the value for ocr_account.access_token
     *
     * @mbg.generated
     */
    public void setAccess_token(String access_token) {
        this.access_token = access_token == null ? null : access_token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ocr_account.expires_in
     *
     * @return the value of ocr_account.expires_in
     *
     * @mbg.generated
     */
    public String getExpires_in() {
        return expires_in;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ocr_account.expires_in
     *
     * @param expires_in the value for ocr_account.expires_in
     *
     * @mbg.generated
     */
    public void setExpires_in(String expires_in) {
        this.expires_in = expires_in == null ? null : expires_in.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ocr_account.effective_time
     *
     * @return the value of ocr_account.effective_time
     *
     * @mbg.generated
     */
    public Date getEffective_time() {
        return effective_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ocr_account.effective_time
     *
     * @param effective_time the value for ocr_account.effective_time
     *
     * @mbg.generated
     */
    public void setEffective_time(Date effective_time) {
        this.effective_time = effective_time;
    }
}