package com.daxia.mapper;

import com.daxia.entity.OcrAccount;
import java.util.List;

public interface OcrAccountMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ocr_account
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ocr_account
     *
     * @mbg.generated
     */
    int insert(OcrAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ocr_account
     *
     * @mbg.generated
     */
    int insertSelective(OcrAccount record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ocr_account
     *
     * @mbg.generated
     */
    OcrAccount selectByPrimaryKey();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ocr_account
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(OcrAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ocr_account
     *
     * @mbg.generated
     */
    void updateByPrimaryKey(OcrAccount record);
}